### ISSUE TITLE
Custom Object detector for another domain

### ISSUE THREAD

**Issue by akshu281** [wmuron/motpy#1]
Hello Author,

Could you please suggest if this Bayesian tracker can be implemented for another domain along with any deep learning based object detector.

If yes, can you please let me know the changes that is needed to this tracking algorithm ?

Thank You !

**Comment by wmuron** [comment]
The tracker can be used with any source of bounding boxes; they can come from any type of object detection algorithm one can imagine.

A good starting point is to play with https://github.com/wmuron/motpy/blob/master/examples/mot16_challange.py and modify it to ingest raw object detections directly from your deep learning detector.
