### ISSUE TITLE
Feature Request: Include ego motion of camera

### ISSUE THREAD

**Issue by shecker** [wmuron/motpy#10]
Hello, thanks for this awesome library!
Is there any way to include ego motion of camera into motpy to make it more stable? We have quite an accurate camera pose estimation and are in a highly dynamic environment, we believe that on an acceleration/jerk level this may have a large performance boost.
Thanks

**Comment by wmuron** [comment]
Hi, I am glad that you find it useful in your use cases :)
Unfortunately, currently I do not plan to add such a feature in motpy, although it definitely sounds like and interesting improvement. 
Best,
Wiktor M

**Comment by Tetsujinfr** [comment]
Looks kike a wonderful feature to add to the library no? Is the issue that the Kalman filter would have to be completely re-written or something else?
