### ISSUE TITLE
Explanation of function arguments

### ISSUE THREAD

**Issue by Blissbill** [wmuron/motpy#12]
Hello your library is very good thank you
But could you please clarify what the arguments to motpy.model.model?

**Comment by haviduck** [comment]
http://greg.czerniak.info/guides/kalman1/

**Comment by wmuron** [comment]
@haviduck pointed a nice explanation of Kalman filter parameters. Also, you can have a deeper dive by checking out https://github.com/rlabbe/Kalman-and-Bayesian-Filters-in-Python/
