### ISSUE TITLE
question: any suggestions on how to speed up?

### ISSUE THREAD

**Issue by simonm3** [wmuron/motpy#14]
Very clearly written package and all works well with little effort so thanks for that. Have it working on Raspberry pi with coral TPU for the detection. 

With 100 items tracked on a static camera tracking time may be 80ms per frame and I can get 5fps end to end in real time. However with 200 items being tracked and moving camera tracking time is 300ms per frame and sometimes over 1 second per frame. Do you have any suggestions as to how to speed this up? I wonder if it could be done on TPU but I guess that would mean rewriting it in tensorflow.

**Comment by wmuron** [comment]
@simonm3 A significant speedup could be achieved by simply modifying the tracker implementation to skip the update/predict step completely (so that observation is used directly as is, and box is updated naively).

**Comment by simonm3** [comment]
Thanks. Good point. In this case camera is moving so can also shift all boxes with the camera to get a better match.

In practice higher fps is mainly for fast moving items. Once there are 400 in one frame it is so crowded that nothing moves fast. In this situation even 1 fps gives good results.
