### ISSUE TITLE
dt of MultiObjectTracker not passed into Tracker

### ISSUE THREAD

**Issue by IreneLian** [wmuron/motpy#18]
https://github.com/wmuron/motpy/blob/be8fb9fb0a010a1cd1f8a8751a7001f80366f724/motpy/tracker.py#L311

new tracker always has dt=1/24

**Comment by wmuron** [comment]
Good catch, it's definitely a case. I've merged a bugfix to master, please check it out.

Soon there will be a small update to the library, so it'll be a part of version 0.0.10
