### ISSUE TITLE
Should matching follows after tracker.predict()?

### ISSUE THREAD

**Issue by IreneLian** [wmuron/motpy#19]
```
        # filter out empty detections
        detections = [det for det in detections if det.box is not None]

        logger.debug('step with %d detections' % len(detections))
        matches = self.matching_fn(self.trackers, detections)
        logger.debug('matched %d pairs' % len(matches))

        # all trackers: predict
        for t in self.trackers:
            t.predict()
```

Now it precedes prediction which seems conflict with MOT pipeline:
 
![image](https://user-images.githubusercontent.com/16590352/133884370-50bb410a-3286-4c54-a9a6-09d60c835bd4.png)

**Comment by wmuron** [comment]
It sounds like a reasonable adjustment to the overall algorithm, although I am not sure to what extent inverting these two steps affects the final performance. Did you run any experiments that might quantify that?

**Comment by IreneLian** [comment]
I got some bad cases on fast moving objects. It highly overlaps with predicted bounding box but has zero IOU with previous frame bounding box. Matching before predict() causes id switch in this situation.

**Comment by wmuron** [comment]
I did some tests and there seems to be a minor improvement, so I merged the fix to master.
