### ISSUE TITLE
2d multi object tracking video

### ISSUE THREAD

**Issue by wmuron** [wmuron/motpy#23]
https://user-images.githubusercontent.com/5874874/134305624-d6358cb1-39f8-4499-8a7b-64745f4795a6.mp4

**Comment by nniv-cmyk** [comment]
@wmuron Thank you for sharing your project.
where are the track IDs, for instance `4e8c3656` being generated in the code? can I change to incrementally show integers, say ID#1, ID#2, ID#3 ... and so forth?
