### ISSUE TITLE
Tracker detection always create, never track

### ISSUE THREAD

**Issue by Hantoo** [wmuron/motpy#3]
Hi,

I have some code which is generating blobs from a background subtraction method. Each frame, I have the boxes of the blobs. In each frame there is a possibility that the blob disappears or appears The blobs are always white against a black background.

I've been trying to input the rectangle blobs each frame however it constantly creates a tracker and never actually tracks them. What the best way to get around this? I can't not give the tracker the detection as there may be a new detection every frame.

**Comment by wmuron** [comment]
Could you please explain a bit more what do you mean by the statement that the library creates a tracker and does not track the objects? It sounds like your scenario is a typical case of processing unassigned detections (bounding boxes) into "identified" tracks, so it is not that different from the examples provided, e.g. see https://github.com/wmuron/motpy/blob/master/examples/2d_multi_object_tracking.py 

If I understand correctly, in each frame you detect blobs of white pixel groups, then for each blob you calculate the bounding box in `[xmin, ymin, xmax, ymax]` format and then call the previously created MultiObjectTracker instance with a `step` function and a list of all of the bounding boxes for a current frame, right?

Do you call a `step` on every frame for which you are calculating the object boxes? Did you confirm that the boxes are visually correct - e.g. there is a substantial overlap between frames? If the answer is yes and the bounding boxes are not missing in majority of frames (some misdetections are allowed) the `active_tracks` method should provide you with active and confirmed tracks.

**Comment by Hantoo** [comment]
So every time I move, and the blobs move, it creates a new tracker for all movements.
This is what I see in my console:
`
2020-05-02 15:41:15.658 | DEBUG    | motpy.tracker:__init__:59 - creating new object tracker with {'order_pos': 1, 'dim_pos': 2, 'order_size': 0, 'dim_size': 2, 'q_var_pos': 5000.0, 'r_var_pos': 0.1} and id d526d73e-be1b-4041-bde1-1e0e957fe25d

2020-05-02 15:41:15.662 | DEBUG    | motpy.tracker:__init__:59 - creating new object tracker with {'order_pos': 1, 'dim_pos': 2, 'order_size': 0, 'dim_size': 2, 'q_var_pos': 5000.0, 'r_var_pos': 0.1} and id 7dce68d5-5b32-467a-ab90-0985cc1fba0b

2020-05-02 15:41:15.667 | DEBUG    | motpy.tracker:__init__:59 - creating new object tracker with {'order_pos': 1, 'dim_pos': 2, 'order_size': 0, 'dim_size': 2, 'q_var_pos': 5000.0, 'r_var_pos': 0.1} and id 3fd50513-542b-42cc-9716-c9f2200f1b9a

2020-05-02 15:41:15.674 | DEBUG    | motpy.tracker:__init__:59 - creating new object tracker with {'order_pos': 1, 'dim_pos': 2, 'order_size': 0, 'dim_size': 2, 'q_var_pos': 5000.0, 'r_var_pos': 0.1} and id 4c7f5655-ecb7-429f-81ec-fb6c07d0d939

2020-05-02 15:41:15.679 | DEBUG    | motpy.tracker:__init__:59 - creating new object tracker with {'order_pos': 1, 'dim_pos': 2, 'order_size': 0, 'dim_size': 2, 'q_var_pos': 5000.0, 'r_var_pos': 0.1} and id f7447369-5b1b-4160-b11e-ee7f698ff7a3

2020-05-02 15:41:15.683 | DEBUG    | motpy.tracker:__init__:59 - creating new object tracker with {'order_pos': 1, 'dim_pos': 2, 'order_size': 0, 'dim_size': 2, 'q_var_pos': 5000.0, 'r_var_pos': 0.1} and id 5738ed61-5d44-42bd-bd70-849c5982a18c

`


This is my code

```
while(1):
  camFrame = cap.read()
  if camFrame is None:
    break
  image = imutils.resize(camFrame, width=800)
  if W is None or H is None:
    (H, W) = image.shape[:2]
  #ret, camFrame = cap.read()
  #if not ret:z
  #  break
  fgmask = fgbg.apply(image)


  gray = fgmask#= cv2.cvtColor(fgmask, cv2.COLOR_GRAY2GRAY)
  rgb = cv2.cvtColor(camFrame, cv2.COLOR_BGR2RGB)
  blurred = cv2.GaussianBlur(gray, (11, 11), 0)

  # threshold the image to reveal light regions in the
  # blurred gray
  thresh = cv2.threshold(gray, 200, 255, cv2.THRESH_BINARY)[1]

  # perform a series of erosions and dilations to remove
  # any small blobs of noise from the thresholded image
  thresh = cv2.erode(thresh, None, iterations=2)
  thresh = cv2.dilate(thresh, None, iterations=4)

  # perform a connected component analysis on the thresholded
  # image, then initialize a mask to store only the "large"
  # components
  labels = measure.label(thresh, connectivity=2, background=0)
  mask = np.zeros(thresh.shape, dtype="uint8")
  # prepare multi object tracker
  model_spec = {'order_pos': 1, 'dim_pos': 2,
                'order_size': 0, 'dim_size': 2,
                'q_var_pos': 5000., 'r_var_pos': 0.1}

  dt = 1 / 10.0  # assume 10 fps
  tracker = MultiObjectTracker(dt=dt, model_spec=model_spec)

  # loop over the unique components
  for label in np.unique(labels):
    # if this is the background label, ignore it
    if label == 0:
      continue

    # otherwise, construct the label mask and count the
    # number of pixels 
    labelMask = np.zeros(thresh.shape, dtype="uint8")
    labelMask[labels == label] = 255
    numPixels = cv2.countNonZero(labelMask)

    # if the number of pixels in the component is sufficiently
    # large, then add it to our mask of "large blobs"
    if numPixels > 100:
      mask = cv2.add(mask, labelMask)

  # find the contours in the mask, then sort them from left to
  # right
  status = "waiting"
  trackers = []
  # check to see if we should run a more computationally expensive
  # object detection method to aid our tracker
  #if totalFrames % 4 == 0:
  # set the status and initialize our new set of object trackers
  status = "Detecting"
  trackers = []
  rects = []
  cnts = cv2.findContours(mask.copy(), cv2.RETR_EXTERNAL,
    cv2.CHAIN_APPROX_SIMPLE)
  if len(cnts) > 0:
    print(len(cnts))
    cnts = imutils.grab_contours(cnts)
    if len(cnts) > 0:
        cnts = contours.sort_contours(cnts)[0]
        # loop over the contours
        
        for (i, c) in enumerate(cnts):
          # draw the bright spot on the image
          (x, y, w, h) = cv2.boundingRect(c)
          rects.append([x,y,x+w,y+h])
          ((cX, cY), radius) = cv2.minEnclosingCircle(c)
          cv2.circle(image, (int(cX), int(cY)), int(radius),(0, 0, 255), 3)
          cv2.putText(image, "#{}".format(i + 1), (x, y - 15),
            cv2.FONT_HERSHEY_SIMPLEX, 0.45, (0, 0, 255), 2)
          #print(x, y, w, h)
  detections = [Detection(box=bbox) for bbox in rects]
  active_tracks = tracker.step(detections)
  tracks = tracker.active_tracks(min_steps_alive=3)
  # for det in detections:
  #   draw_detection(image, det)

  for track in tracks:
    draw_track(image, track)

```

**Comment by wmuron** [comment]
Please move the part with `MultiObjectTracker` creation before the while loop. Currently it is called on every new frame, meaning that you call `step` always on fresh state tracker. You only need to create a tracker once and call step on every detecting frame.
