### ISSUE TITLE
Very good libs ! but how to merge the tracking result to the source list? always error of `IndexError: list index out of range`

### ISSUE THREAD

**Issue by 12343954** [wmuron/motpy#4]
1. list_detect2 contains detection bbox，not rotated bbox
2. list_detect3 is the detections list. i want to merge the track.id to list_detect3 
3. idxs is a dict, key is track.id, value is a int. it means to convert uuid to int id.

questions is
1. how to merge the tracking result to list_detect3？my code is often crash.
2. tracking result is more than source list sometimes. what can i do？
3. tracking result is not stable，what can i do? 

```
list_detect2 = [Detection(box=bbox, score=1) for bbox in list_detect2]
active_tracks = tracker.step(detections=list_detect2)

for index, track in enumerate(active_tracks):
    if track.id in idxs:
        if index < lenght_list3:
            list_detect3[index].append(idxs.get(track.id))
        # else:
        #     print("===============================")
        #     print("track [%s] not in list_detect3[%s]" %
        #           (index, lenght_list3))
        #     print("===============================")
    else:
        if index >= lenght_list3:
            counter += 1
            continue
        idxs[track.id] = counter
        list_detect3[index].append(counter)
        counter += 1
```

![ezgif-7-5c2686a9ffbd](https://user-images.githubusercontent.com/1804003/93036474-8bc6fd00-f672-11ea-9033-3b0eca781e2d.gif)

**Comment by haviduck** [comment]
1 and 2 you could try using defaultdict(set) and add to it. you can even store unique key val for multiclass tracking. defaultdict(set) is unique and will keep a true count without being messy.

tracker optimization  differs from case to case. you gotta use his parameters and tweak to what fits you

**Comment by wmuron** [comment]
Closing due to lack of response from original author.

**Comment by haviduck** [comment]
yo @wmuron you know the id switch issue right, its apperant in most trackers. currently im solving that by using 1 tracker by class. however im stuck with a conondrum. when 1 object gets falsely detected by to trackers due to feature similarity i fail to see a way to really do iou since the tracks are separete.  how would you approach something like that? merge tracks, calculate iou and squash the least scored one? sorry for replying to closed thread.
