### ISSUE TITLE
Installation fail on raspberry pi 4

### ISSUE THREAD

**Issue by zzzeddy** [wmuron/motpy#5]
Hello,

I'm in trouble to install & test motpy on my RPI 4B.
It's working well in Ubuntu on PC. 

After git clone, I changed 'python' to 'python3' in Makefile then run 
$ sudo make install-develop

Error messages are as follows,

--- start of message ---
python3 setup.py develop
running develop
running egg_info
writing motpy.egg-info/PKG-INFO
writing dependency_links to motpy.egg-info/dependency_links.txt
writing requirements to motpy.egg-info/requires.txt
writing top-level names to motpy.egg-info/top_level.txt
reading manifest file 'motpy.egg-info/SOURCES.txt'
writing manifest file 'motpy.egg-info/SOURCES.txt'
running build_ext
Creating /usr/local/lib/python3.8/dist-packages/motpy.egg-link (link to .)
motpy 0.0.8 is already the active version in easy-install.pth

Installed /home/sol/proj/Tracking/motpy
Processing dependencies for motpy==0.0.8
Searching for matplotlib
Reading https://pypi.org/simple/matplotlib/
Downloading https://files.pythonhosted.org/packages/7b/b3/7c48f648bf83f39d4385e0169d1b68218b838e185047f7f613b1cfc57947/matplotlib-3.3.3.tar.gz#sha256=b1b60c6476c4cfe9e5cf8ab0d3127476fd3d5f05de0f343a452badaad0e4bdec
Best match: matplotlib 3.3.3
Processing matplotlib-3.3.3.tar.gz
Writing /tmp/easy_install-1lt1s5ie/matplotlib-3.3.3/setup.cfg
Running matplotlib-3.3.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-1lt1s5ie/matplotlib-3.3.3/egg-dist-tmp-y7m_sz5d
UPDATING build/lib.linux-aarch64-3.8/matplotlib/_version.py
set build/lib.linux-aarch64-3.8/matplotlib/_version.py to '3.3.3'
error: Setup script exited with error: Failed to download FreeType. Please download one of ['https://downloads.sourceforge.net/project/freetype/freetype2/2.6.1/freetype-2.6.1.tar.gz', 'https://download.savannah.gnu.org/releases/freetype/freetype-2.6.1.tar.gz'] and extract it into build/freetype-2.6.1 at the top-level of the source repository.
make: *** [Makefile.3:5: install-develop] Error 1
sol@sol-rpi:~/proj/Tracking/motpy$ 
--- end of message ---

I download the freetype2  then extract it to motpy/build/ but not working as before.

**Comment by wmuron** [comment]
The problem is related to matplotlib installation, not motpy. I assume that you tried to solve it by installing `libfreetype-devel` (as most related posts propose). If it didn't solve your problem, try to install `pkg-config`, which also might be and issue (see: https://github.com/matplotlib/matplotlib/issues/3029/#issuecomment-44465459).

On another topic, I'd suggest using virtualenv or conda for python environments management; If it's not an option in your case, you can always use bash aliases to make `python` point to `python3`.
